// Code generated by MockGen. DO NOT EDIT.
// Source: ./http_client.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	url "net/url"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockHTTPClient) Delete(ctx context.Context, url string, headers map[string]string) (int, interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, url, headers)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Delete indicates an expected call of Delete.
func (mr *MockHTTPClientMockRecorder) Delete(ctx, url, headers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHTTPClient)(nil).Delete), ctx, url, headers)
}

// DeleteNoUnmarshal mocks base method.
func (m *MockHTTPClient) DeleteNoUnmarshal(ctx context.Context, url string, headers map[string]string) (int, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNoUnmarshal", ctx, url, headers)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteNoUnmarshal indicates an expected call of DeleteNoUnmarshal.
func (mr *MockHTTPClientMockRecorder) DeleteNoUnmarshal(ctx, url, headers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNoUnmarshal", reflect.TypeOf((*MockHTTPClient)(nil).DeleteNoUnmarshal), ctx, url, headers)
}

// Get mocks base method.
func (m *MockHTTPClient) Get(ctx context.Context, url string, queryValues url.Values, headers map[string]string) (int, interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, url, queryValues, headers)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockHTTPClientMockRecorder) Get(ctx, url, queryValues, headers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHTTPClient)(nil).Get), ctx, url, queryValues, headers)
}

// GetNoUnmarshal mocks base method.
func (m *MockHTTPClient) GetNoUnmarshal(ctx context.Context, url string, queryValues url.Values, headers map[string]string) (int, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoUnmarshal", ctx, url, queryValues, headers)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetNoUnmarshal indicates an expected call of GetNoUnmarshal.
func (mr *MockHTTPClientMockRecorder) GetNoUnmarshal(ctx, url, queryValues, headers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoUnmarshal", reflect.TypeOf((*MockHTTPClient)(nil).GetNoUnmarshal), ctx, url, queryValues, headers)
}

// Patch mocks base method.
func (m *MockHTTPClient) Patch(ctx context.Context, url string, headers map[string]string, reqParam interface{}) (int, interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", ctx, url, headers, reqParam)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Patch indicates an expected call of Patch.
func (mr *MockHTTPClientMockRecorder) Patch(ctx, url, headers, reqParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockHTTPClient)(nil).Patch), ctx, url, headers, reqParam)
}

// PatchNoUnmarshal mocks base method.
func (m *MockHTTPClient) PatchNoUnmarshal(ctx context.Context, url string, headers map[string]string, reqParam interface{}) (int, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchNoUnmarshal", ctx, url, headers, reqParam)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PatchNoUnmarshal indicates an expected call of PatchNoUnmarshal.
func (mr *MockHTTPClientMockRecorder) PatchNoUnmarshal(ctx, url, headers, reqParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchNoUnmarshal", reflect.TypeOf((*MockHTTPClient)(nil).PatchNoUnmarshal), ctx, url, headers, reqParam)
}

// Post mocks base method.
func (m *MockHTTPClient) Post(ctx context.Context, url string, headers map[string]string, reqParam interface{}) (int, interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", ctx, url, headers, reqParam)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Post indicates an expected call of Post.
func (mr *MockHTTPClientMockRecorder) Post(ctx, url, headers, reqParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockHTTPClient)(nil).Post), ctx, url, headers, reqParam)
}

// PostNoUnmarshal mocks base method.
func (m *MockHTTPClient) PostNoUnmarshal(ctx context.Context, url string, headers map[string]string, reqParam interface{}) (int, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostNoUnmarshal", ctx, url, headers, reqParam)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PostNoUnmarshal indicates an expected call of PostNoUnmarshal.
func (mr *MockHTTPClientMockRecorder) PostNoUnmarshal(ctx, url, headers, reqParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostNoUnmarshal", reflect.TypeOf((*MockHTTPClient)(nil).PostNoUnmarshal), ctx, url, headers, reqParam)
}

// Put mocks base method.
func (m *MockHTTPClient) Put(ctx context.Context, url string, headers map[string]string, reqParam interface{}) (int, interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, url, headers, reqParam)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Put indicates an expected call of Put.
func (mr *MockHTTPClientMockRecorder) Put(ctx, url, headers, reqParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockHTTPClient)(nil).Put), ctx, url, headers, reqParam)
}

// PutNoUnmarshal mocks base method.
func (m *MockHTTPClient) PutNoUnmarshal(ctx context.Context, url string, headers map[string]string, reqParam interface{}) (int, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutNoUnmarshal", ctx, url, headers, reqParam)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PutNoUnmarshal indicates an expected call of PutNoUnmarshal.
func (mr *MockHTTPClientMockRecorder) PutNoUnmarshal(ctx, url, headers, reqParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutNoUnmarshal", reflect.TypeOf((*MockHTTPClient)(nil).PutNoUnmarshal), ctx, url, headers, reqParam)
}
