// Code generated by MockGen. DO NOT EDIT.
// Source: ./oauth2.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	oauth "github.com/AISHU-Technology/kweaver-go-lib/oauth"
	rest "github.com/AISHU-Technology/kweaver-go-lib/rest"
	gomock "github.com/golang/mock/gomock"
)

// MockOAuth2 is a mock of OAuth2 interface.
type MockOAuth2 struct {
	ctrl     *gomock.Controller
	recorder *MockOAuth2MockRecorder
}

// MockOAuth2MockRecorder is the mock recorder for MockOAuth2.
type MockOAuth2MockRecorder struct {
	mock *MockOAuth2
}

// NewMockOAuth2 creates a new mock instance.
func NewMockOAuth2(ctrl *gomock.Controller) *MockOAuth2 {
	mock := &MockOAuth2{ctrl: ctrl}
	mock.recorder = &MockOAuth2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuth2) EXPECT() *MockOAuth2MockRecorder {
	return m.recorder
}

// NewOAuth2HTTPClient mocks base method.
func (m *MockOAuth2) NewOAuth2HTTPClient(info oauth.AppAccountInfo) rest.HTTPClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewOAuth2HTTPClient", info)
	ret0, _ := ret[0].(rest.HTTPClient)
	return ret0
}

// NewOAuth2HTTPClient indicates an expected call of NewOAuth2HTTPClient.
func (mr *MockOAuth2MockRecorder) NewOAuth2HTTPClient(info interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewOAuth2HTTPClient", reflect.TypeOf((*MockOAuth2)(nil).NewOAuth2HTTPClient), info)
}

// NewOAuth2HTTPClientWithOptions mocks base method.
func (m *MockOAuth2) NewOAuth2HTTPClientWithOptions(info oauth.AppAccountInfo, opts rest.HttpClientOptions) rest.HTTPClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewOAuth2HTTPClientWithOptions", info, opts)
	ret0, _ := ret[0].(rest.HTTPClient)
	return ret0
}

// NewOAuth2HTTPClientWithOptions indicates an expected call of NewOAuth2HTTPClientWithOptions.
func (mr *MockOAuth2MockRecorder) NewOAuth2HTTPClientWithOptions(info, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewOAuth2HTTPClientWithOptions", reflect.TypeOf((*MockOAuth2)(nil).NewOAuth2HTTPClientWithOptions), info, opts)
}
